"""make whatsapp channels optional in hotel setup

Revision ID: b0d507cdd216
Revises: 287aba07a4c0
Create Date: 2026-04-04 08:09:54.108616
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d507cdd216'
down_revision: Union[str, None] = '287aba07a4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('hotels', 'whatsapp_phone_number_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Meta WhatsApp Business phone number ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'whatsapp_phone_number_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Meta WhatsApp Business phone number ID')
    op.alter_column('hotels', 'whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
